  INFO root [2017-12-20 16:39:52,444] - 
  INFO root [2017-12-20 16:39:52,444] - -----------------------------------------------------------------------------------------


  INFO root [2017-12-20 16:39:52,445] - Resmgr::initialize: KBE_ROOT=I:/KBE/kbengine-1.0.0/
  INFO root [2017-12-20 16:39:52,445] - Resmgr::initialize: KBE_RES_PATH=I:/KBE/kbengine-1.0.0/kbe/res/;I:/KBE/kbengine-1.0.0/balls_server_assets/;I:/KBE/kbengine-1.0.0/balls_server_assets/scripts/;I:/KBE/kbengine-1.0.0/balls_server_assets/res/
  INFO root [2017-12-20 16:39:52,445] - Resmgr::initialize: KBE_BIN_PATH=I:/KBE/kbengine-1.0.0/kbe/bin/server/
  INFO root [2017-12-20 16:39:52,453] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:20013 )
  INFO root [2017-12-20 16:39:52,453] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.100.93:20013, SOMAXCONN=128.
  INFO root [2017-12-20 16:39:52,455] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:13995 )
  INFO root [2017-12-20 16:39:52,455] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.100.93:13995, SOMAXCONN=128.
  INFO root [2017-12-20 16:39:52,455] - server-configs:
  INFO root [2017-12-20 16:39:52,455] - 	internalAddr : 192.168.100.93:13995
  INFO root [2017-12-20 16:39:52,455] - 	externalAddr : 192.168.100.93:20013
  INFO root [2017-12-20 16:39:52,455] - 	componentID : 9000
  INFO root [2017-12-20 16:39:52,781] - Components::findLogger: found logger, addr:192.168.100.93:13990
  INFO root [2017-12-20 16:39:52,781] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2017-12-20 16:39:52,781] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2017-12-20 16:39:52,785] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 15:24:44 Nov 23 2017. AppID: 9000. UID: 10103. PID: 6112 ----
  INFO root [2017-12-20 16:39:52,785] - Server :         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz with 4194303kB RAM
  INFO root [2017-12-20 16:39:52,786] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2017-12-20 16:39:52,786] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2017-12-20 16:39:52,914] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 16:39:52,914] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 16:39:52,914] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 16:39:52,918] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 16:39:52,918] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 16:39:52,918] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 16:39:52,919] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 16:39:52,954] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 16:39:52,988] - Script::install(): is successfully, Python=(3.4.2 (default, Nov 23 2017, 15:24:43) [MSC v.1800 32 bit (Intel)])!
  INFO root [2017-12-20 16:39:52,988] - Script::install(): KBExtra is successfully!
S_INFO root [2017-12-20 16:39:52,996] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2017-12-20 16:39:52,996] - TelnetServer server is running on port 31000
  INFO root [2017-12-20 16:39:53,260] - ---- loginapp is running ----
 DEBUG root [2017-12-20 16:39:53,261] - Components::process(): Request for the process of identity...
  WARN root [2017-12-20 16:39:59,304] - Forwarding logs to logger[192.168.100.93:13990/0/0/0]...
 ERROR root [2017-12-20 16:49:23,545] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 16:49:23,549] - The following logs sent to logger failed:
  WARN root [2017-12-20 16:49:23,549] - ==> [2017-12-20 16:49:23 545] TCPPacketReceiver::processPendingEvents(192.168.100.93:13990): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 16:49:23,549] - ==> [2017-12-20 16:49:23 545] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2017-12-20 16:49:23,625] - TCPPacketReceiver::processPendingEvents(192.168.100.93:13991): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 16:49:23,627] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 16:49:23,630] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2017-12-20 16:49:23,630] - onLoginAppShutDown()
  INFO root [2017-12-20 16:49:23,631] - Shutdowner::onShutdown: shutting down
  INFO root [2017-12-20 16:49:23,631] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 16:49:23,631] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 16:49:23,632] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 16:49:23,642] - Script::uninstall(): is successfully!
 DEBUG root [2017-12-20 16:49:23,643] - ThreadPool::destroy(): starting size 2.
  WARN root [2017-12-20 16:49:23,943] - ThreadPool::destroy(): waiting for thread(2)[0x223928,0x2238c0,], try=1
  INFO root [2017-12-20 16:49:51,210] - 
  INFO root [2017-12-20 16:49:51,212] - -----------------------------------------------------------------------------------------


  INFO root [2017-12-20 16:49:51,213] - Resmgr::initialize: KBE_ROOT=I:/KBE/kbengine-1.0.0/
  INFO root [2017-12-20 16:49:51,213] - Resmgr::initialize: KBE_RES_PATH=I:/KBE/kbengine-1.0.0/kbe/res/;I:/KBE/kbengine-1.0.0/balls_server_assets/;I:/KBE/kbengine-1.0.0/balls_server_assets/scripts/;I:/KBE/kbengine-1.0.0/balls_server_assets/res/
  INFO root [2017-12-20 16:49:51,213] - Resmgr::initialize: KBE_BIN_PATH=I:/KBE/kbengine-1.0.0/kbe/bin/server/
  INFO root [2017-12-20 16:49:51,222] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:20013 )
  INFO root [2017-12-20 16:49:51,222] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.100.93:20013, SOMAXCONN=128.
  INFO root [2017-12-20 16:49:51,223] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:14411 )
  INFO root [2017-12-20 16:49:51,224] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.100.93:14411, SOMAXCONN=128.
  INFO root [2017-12-20 16:49:51,224] - server-configs:
  INFO root [2017-12-20 16:49:51,224] - 	internalAddr : 192.168.100.93:14411
  INFO root [2017-12-20 16:49:51,224] - 	externalAddr : 192.168.100.93:20013
  INFO root [2017-12-20 16:49:51,224] - 	componentID : 9000
  INFO root [2017-12-20 16:49:51,609] - Components::findLogger: found logger, addr:192.168.100.93:14406
  INFO root [2017-12-20 16:49:51,609] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2017-12-20 16:49:51,609] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2017-12-20 16:49:51,613] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 15:24:44 Nov 23 2017. AppID: 9000. UID: 10103. PID: 8548 ----
  INFO root [2017-12-20 16:49:51,614] - Server :         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz with 4194303kB RAM
  INFO root [2017-12-20 16:49:51,614] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2017-12-20 16:49:51,614] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2017-12-20 16:49:51,741] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 16:49:51,741] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 16:49:51,742] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 16:49:51,745] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 16:49:51,745] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 16:49:51,745] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 16:49:51,746] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 16:49:51,779] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 16:49:51,813] - Script::install(): is successfully, Python=(3.4.2 (default, Nov 23 2017, 15:24:43) [MSC v.1800 32 bit (Intel)])!
  INFO root [2017-12-20 16:49:51,813] - Script::install(): KBExtra is successfully!
S_INFO root [2017-12-20 16:49:51,816] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2017-12-20 16:49:51,816] - TelnetServer server is running on port 31000
  INFO root [2017-12-20 16:49:52,062] - ---- loginapp is running ----
 DEBUG root [2017-12-20 16:49:52,063] - Components::process(): Request for the process of identity...
  WARN root [2017-12-20 16:49:58,103] - Forwarding logs to logger[192.168.100.93:14406/0/0/0]...
 ERROR root [2017-12-20 17:04:50,240] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 17:04:50,251] - The following logs sent to logger failed:
  WARN root [2017-12-20 17:04:50,252] - ==> [2017-12-20 17:04:50 239] TCPPacketReceiver::processPendingEvents(192.168.100.93:14406): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 17:04:50,252] - ==> [2017-12-20 17:04:50 241] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2017-12-20 17:04:50,324] - TCPPacketReceiver::processPendingEvents(192.168.100.93:14408): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 17:04:50,326] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 17:04:50,332] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2017-12-20 17:04:50,340] - onLoginAppShutDown()
  INFO root [2017-12-20 17:04:50,340] - Shutdowner::onShutdown: shutting down
  INFO root [2017-12-20 17:04:50,340] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 17:04:50,341] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 17:04:50,352] - Script::uninstall(): is successfully!
 DEBUG root [2017-12-20 17:04:50,352] - ThreadPool::destroy(): starting size 2.
  WARN root [2017-12-20 17:04:50,652] - ThreadPool::destroy(): waiting for thread(2)[0x453928,0x4538c0,], try=1
  INFO root [2017-12-20 17:04:57,786] - 
  INFO root [2017-12-20 17:04:57,786] - -----------------------------------------------------------------------------------------


  INFO root [2017-12-20 17:04:57,786] - Resmgr::initialize: KBE_ROOT=I:/KBE/kbengine-1.0.0/
  INFO root [2017-12-20 17:04:57,787] - Resmgr::initialize: KBE_RES_PATH=I:/KBE/kbengine-1.0.0/kbe/res/;I:/KBE/kbengine-1.0.0/balls_server_assets/;I:/KBE/kbengine-1.0.0/balls_server_assets/scripts/;I:/KBE/kbengine-1.0.0/balls_server_assets/res/
  INFO root [2017-12-20 17:04:57,787] - Resmgr::initialize: KBE_BIN_PATH=I:/KBE/kbengine-1.0.0/kbe/bin/server/
  INFO root [2017-12-20 17:04:57,795] - NetworkInterface::recreateListeningSocket(EXTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:20013 )
  INFO root [2017-12-20 17:04:57,795] - NetworkInterface::recreateListeningSocket(EXTERNAL): address 192.168.100.93:20013, SOMAXCONN=128.
  INFO root [2017-12-20 17:04:57,797] - NetworkInterface::recreateListeningSocket(INTERNAL): bound to all interfaces with default route interface on 192.168.100.93 ( 192.168.100.93:15057 )
  INFO root [2017-12-20 17:04:57,797] - NetworkInterface::recreateListeningSocket(INTERNAL): address 192.168.100.93:15057, SOMAXCONN=128.
  INFO root [2017-12-20 17:04:57,797] - server-configs:
  INFO root [2017-12-20 17:04:57,797] - 	internalAddr : 192.168.100.93:15057
  INFO root [2017-12-20 17:04:57,797] - 	externalAddr : 192.168.100.93:20013
  INFO root [2017-12-20 17:04:57,797] - 	componentID : 9000
  INFO root [2017-12-20 17:04:58,170] - Components::findLogger: found logger, addr:192.168.100.93:15031
  INFO root [2017-12-20 17:04:58,170] - Components::addComponent: reset orderLog, uid=10103!
  INFO root [2017-12-20 17:04:58,170] - Components::addComponent[logger], uid=10103, componentID=2000, globalorderid=1, grouporderid=1, totalcount=1
  INFO root [2017-12-20 17:05:02,782] - ---- loginapp Version: 1.0.0. ScriptVersion: 0.1.0. Protocol: A16A7477E55D6AEDCD48345D2B50A665. Config: Debug X86. Built: 15:24:44 Nov 23 2017. AppID: 9000. UID: 10103. PID: 10204 ----
  INFO root [2017-12-20 17:05:02,783] - Server :         Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz with 4194303kB RAM
  INFO root [2017-12-20 17:05:02,784] - ThreadPool::createThreadPool: creating  threadpool...
  INFO root [2017-12-20 17:05:02,784] - ThreadPool::createThreadPool: successfully(2), newThreadCount=1, normalMaxThreadCount=2, maxThreadCount=8
 DEBUG root [2017-12-20 17:05:02,911] - Script::install_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 17:05:02,912] - Script::install_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 17:05:02,912] - Script::install_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 17:05:02,915] - Script::install_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 17:05:02,915] - Script::install_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 17:05:02,915] - Script::install_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 17:05:02,916] - Script::install_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 17:05:02,949] - Script::install_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 17:05:02,982] - Script::install(): is successfully, Python=(3.4.2 (default, Nov 23 2017, 15:24:43) [MSC v.1800 32 bit (Intel)])!
  INFO root [2017-12-20 17:05:02,982] - Script::install(): KBExtra is successfully!
S_INFO root [2017-12-20 17:05:02,984] - onLoginAppReady: bootstrapGroupIndex=0, bootstrapGlobalIndex=0
  INFO root [2017-12-20 17:05:02,984] - TelnetServer server is running on port 31000
  INFO root [2017-12-20 17:05:03,226] - ---- loginapp is running ----
 DEBUG root [2017-12-20 17:05:03,226] - Components::process(): Request for the process of identity...
  WARN root [2017-12-20 17:05:09,268] - Forwarding logs to logger[192.168.100.93:15031/0/0/0]...
 ERROR root [2017-12-20 18:42:56,127] - Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 18:42:56,128] - The following logs sent to logger failed:
  WARN root [2017-12-20 18:42:56,128] - ==> [2017-12-20 18:42:56 127] TCPPacketReceiver::processPendingEvents(192.168.100.93:15031): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 18:42:56,129] - ==> [2017-12-20 18:42:56 128] Components::removeComponentByChannel: logger : 2000, Abnormal exit! errorno=10054
  WARN root [2017-12-20 18:42:56,181] - TCPPacketReceiver::processPendingEvents(192.168.100.93:15036): Throwing REASON_GENERAL_NETWORK - WSAECONNRESET
 ERROR root [2017-12-20 18:42:56,182] - Components::removeComponentByChannel: dbmgr : 4000, Abnormal exit! errorno=10054
  INFO root [2017-12-20 18:42:56,182] - Shutdowner::onShutdownBegin: shutting down(period=0, tickPeriod=1)
S_INFO root [2017-12-20 18:42:56,183] - onLoginAppShutDown()
  INFO root [2017-12-20 18:42:56,183] - Shutdowner::onShutdown: shutting down
  INFO root [2017-12-20 18:42:56,183] - Shutdowner::onShutdownEnd: shutting down
 DEBUG root [2017-12-20 18:42:56,183] - Script::uninstall_py_dlls(): PyInit_pyexpat
 DEBUG root [2017-12-20 18:42:56,183] - Script::uninstall_py_dlls(): PyInit__socket
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit__ssl
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit__hashlib
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit_select
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit__ctypes
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit__elementtree
 DEBUG root [2017-12-20 18:42:56,184] - Script::uninstall_py_dlls(): PyInit_unicodedata
  INFO root [2017-12-20 18:42:56,194] - Script::uninstall(): is successfully!
 DEBUG root [2017-12-20 18:42:56,194] - ThreadPool::destroy(): starting size 2.
  WARN root [2017-12-20 18:42:56,494] - ThreadPool::destroy(): waiting for thread(2)[0x443928,0x4438c0,], try=1
